### ISSUE TITLE
 Performance - WFE is used in incorrect scenario for aarch64 cpuRelax #48 

### ISSUE THREAD

**Issue by rob-p** [rob-p/FQFeeder#5]
Moving this issue from [pufferfish #48](https://github.com/COMBINE-lab/pufferfish/issues/48). @dslarm, do you think you could propose a PR here that would address this issue?  For the time being I'd prefer to keep the WFE on x86, but I'm happy to alter the arm path, and especially to remove instructions that stall cores!

**Comment by dslarm** [comment]
@rob-p  - no problem, I have to get approval to contribute first - it'll take 48 hours but should be no issue.

**Comment by rob-p** [comment]
Resolved by https://github.com/rob-p/FQFeeder/pull/6 --- thanks again!
